SELECT 'customer' AS tbl, COUNT(*) FROM customer
UNION ALL SELECT 'address', COUNT(*) FROM address
UNION ALL SELECT 'customer_address', COUNT(*) FROM customer_address
UNION ALL SELECT 'category', COUNT(*) FROM category
UNION ALL SELECT 'product', COUNT(*) FROM product
UNION ALL SELECT 'product_category', COUNT(*) FROM product_category
UNION ALL SELECT 'supplier', COUNT(*) FROM supplier
UNION ALL SELECT 'product_supplier', COUNT(*) FROM product_supplier
UNION ALL SELECT 'warehouse', COUNT(*) FROM warehouse
UNION ALL SELECT 'inventory', COUNT(*) FROM inventory
UNION ALL SELECT 'promotion', COUNT(*) FROM promotion
UNION ALL SELECT 'orders', COUNT(*) FROM orders
UNION ALL SELECT 'order_item', COUNT(*) FROM order_item
UNION ALL SELECT 'payment', COUNT(*) FROM payment
UNION ALL SELECT 'shipment', COUNT(*) FROM shipment
UNION ALL SELECT 'order_promotion', COUNT(*) FROM order_promotion
UNION ALL SELECT 'loyalty_account', COUNT(*) FROM loyalty_account
UNION ALL SELECT 'loyalty_txn', COUNT(*) FROM loyalty_txn;
